### ISSUE TITLE
Why not use our eslint standard (@fastcoder/eslint-config-base) to regulate code?

### ISSUE THREAD

**Issue by calandnong** [asdiver/feel-fish-collection#1]
Description:
I noticed that some of the code in our project doesn't seem to conform to our eslint standard. Our team has defined an eslint standard (@fastcoder/eslint-config-base) that can help us regulate code and improve code quality. However, I found that not everyone is using this standard to write code. I would like to understand why we are not using our own defined eslint standard to regulate code, and how we can ensure that all code in the project follows this standard?

Steps to reproduce:
- Check the code in the project to confirm whether it conforms to the @fastcoder/eslint-config-base standard.
- If there is code that does not conform to the standard, try to find out the reason.
- Discuss how to ensure that all code in the project follows the @fastcoder/eslint-config-base standard.

Expected behavior:
I expect that all code in our project conforms to the @fastcoder/eslint-config-base standard, so that it is easier to maintain and debug the code, and improve code quality.

Actual behavior:
Not everyone is using our own defined eslint standard (@fastcoder/eslint-config-base) to write code, which may lead to inconsistent code quality and make it more difficult to maintain and debug code.

Versions:

- version: none
- project language: JavaScript

Additional information:
We can consider using an eslint plugin in the project to automatically check whether the code conforms to the @fastcoder/eslint-config-base standard, and perform the check before submitting the code. This can ensure that all code in the project conforms to our own defined eslint standard. At the same time, we can also strengthen the promotion and training of this standard, so that everyone can follow this standard to write code.

**Comment by asdiver** [comment]
This is a good question, as described by my repository: this is not a formal project. there is no need for the current level. Of course, if the repository becomes increasingly large in the future, your proposal is essential

**Comment by calandnong** [comment]
@asdiver ok
